### ISSUE TITLE
Escape codes for links aren't always suppressed when not supported

### ISSUE THREAD

**Issue by emojjon** [willmcgugan/rich#1630] opened 2021-10-28 19:02 UTC
### Discussed in https://github.com/willmcgugan/rich/discussions/1625

<div type='discussions-op-text'>

<sup>Originally posted by **emojjon** October 28, 2021</sup>
As I understand it, you can't create an instance of Console that explicitly doesn't use link escape codes. Apparently these codes should be ignored by terminals that don't support them. Sometimes it would be good though, because the codes actually mangles the output in some circumstances.

I hesitate to say exactly how to reproduce this since in my case it involved several ssh logins and strangeness with shell rc-files and what not. Suffice to say it would be nice to be able to turn it off in some circumstances, perhaps even from outside the python code (environment variable?).

Great project by the way. I discovered it yesterday, and I'm looking forward to try and use it myself.</div>

**Comment by willmcgugan** [comment] 2021-11-08 09:30
Closing for now since I can't reproduce. But happy to look at it again if we can narrow down the cause.

**Closed by willmcgugan** 2021-11-08 09:30 UTC
