### ISSUE TITLE
The background of too long code in the traceback may not be rendered properly

### ISSUE THREAD

**Issue by GeekDuanLian** [willmcgugan/rich#30] opened 2020-03-30 21:47 UTC
![image](https://user-images.githubusercontent.com/6257434/77964557-d39ad780-7311-11ea-85ac-1752227e8899.png)
I guess correct rendering won't let the number of rows be rendered?

However, I actually hope that there is an option to ignore the excess of the long code, because I think that traceback is only to facilitate the location of the faulty code line, and it is not necessary to display everything.
The excess can be marked as an ellipsis at the rear.

**Comment by GeekDuanLian** [comment] 2020-03-30 21:54
In fact, the longest line is not shown completely, and some code is not shown after "q"

**Comment by willmcgugan** [comment] 2020-03-30 22:05
Long lines will wrap, and that will push the line numbers down. I think generally it should show all the code, but I like your idea to add an option to clip it.

I think the problem is related to your other issue. It’s not wrapping long words that run over the end of the line correctly.

**Comment by GeekDuanLian** [comment] 2020-03-30 22:22
I would be grateful if there was an option to turn off word wrapping, which would make the tracebacks cleaner and shorter.

**Comment by willmcgugan** [comment] 2020-03-31 13:31
Please try with 0.8.7. I've disabled word wrapping by default. I think most developer are used to viewing code without word wrapping.

**Comment by GeekDuanLian** [comment] 2020-03-31 14:51
Thanks!

But now the code background is not a whole piece? In fact, I hope to cover the entire code area.
![image](https://user-images.githubusercontent.com/6257434/78040360-e826b080-73a1-11ea-9880-c5d04da6f05f.png)

But if this will cause the line number to be rendered, in fact, when the word wrapping is turned off, this problem will be solved by the way.

**Comment by willmcgugan** [comment] 2020-03-31 15:53
Should be fixed in 0.8.8

**Comment by GeekDuanLian** [comment] 2020-03-31 15:57
Thanks a lot! Have a nice day!

**Closed** 2020-03-31 15:57 UTC
