### ISSUE TITLE
[BUG] Color is not outputted on Git Bash

### ISSUE THREAD

**Issue by musse** [willmcgugan/rich#988] opened 2021-02-05 12:50 UTC
**Describe the bug**
When running a Python script using Rich with Git Bash on Windows, color is not outputted.

**To Reproduce**
Simply run the following code on a Git Bash terminal:
```python
import rich

rich.print('[red]This text should be red[/red]')
```

Forcing terminal and/or disabling legacy Windows mode do not work either:
```python
import rich.console

console = rich.console.Console(force_terminal=True, legacy_windows=False)
console.print('[red]This text should be red[/red]')
```

**Platform**
Windows 10, Git Bash (MINGW64)

**Diagnose**

```
$ python -m rich.diagnose
+---------------------- <class 'rich.console.Console'> -----------------------+
| A high level console interface.                                             |
|                                                                             |
| +-------------------------------------------------------------------------+ |
| | <console width=79 None>                                                 | |
| +-------------------------------------------------------------------------+ |
|                                                                             |
|     color_system = None                                                     |
|         encoding = 'cp1252'                                                 |
|             file = <colorama.ansitowin32.StreamWrapper object at            |
|                    0x0203EC88>                                              |
| is_dumb_terminal = False                                                    |
|       is_jupyter = False                                                    |
|      is_terminal = False                                                    |
|   legacy_windows = True                                                     |
|         no_color = False                                                    |
|          options = ConsoleOptions(legacy_windows=True, min_width=1,         |
|                    max_width=79, is_terminal=False, encoding='cp1252',      |
|                    justify=None, overflow=None, no_wrap=False,              |
|                    highlight=None)                                          |
|           record = False                                                    |
|         safe_box = True                                                     |
|             size = ConsoleDimensions(width=79, height=24)                   |
|        soft_wrap = False                                                    |
|           stderr = False                                                    |
|            style = None                                                     |
|         tab_size = 8                                                        |
|            width = 79                                                       |
+-----------------------------------------------------------------------------+

$ python -m rich._windows
platform="Windows"
WindowsConsoleFeatures(vt=False, truecolor=False)

$ pip freeze | grep rich
rich==9.10.0
```

**Additional info**

I've investigated the Rich coding and [the problematic code seem to be related to the `colorama.init()` call](https://github.com/willmcgugan/rich/blob/v9.10.0/rich/console.py#L379-L387).

If I comment out the call to `colorama.init()` and set `force_terminal` to `True`, then I get color on the output. Git Bash emulates BASH on Windows, so I assume it is expecting ANSI codes. However, `detect_legacy_windows()` is incorrectly returning `True`; therefore, `colorama.init()` is called and ANSI codes are not outputted.

I think the fix would be to make `detect_legacy_windows()` return `False` when running on Git Bash/MINGW, but I'm not sure how to do it.

**Comment by musse** [comment] 2021-02-05 13:04
Relevant issue: https://github.com/tartley/colorama/issues/224

**Comment by willmcgugan** [comment] 2021-02-05 14:22
Thanks for doing the research there. Detecting terminal capabilities on Windows is messy. I think that detecting the TERM env var may be enough to disable the legacy_windows check. I'll give it some thought. I'd also accept a PR if you want to tackle it.

**Comment by musse** [comment] 2021-02-05 15:00
I can give it a try. Do you think it makes sense to handle the `colorama.init()` on the `Console` class depending on the value of `legacy_windows`? Doing so would allow to easily disable the colorama call by forcing `legacy_windows` to `False`. We could use [colorama's `deinit()` and `reinit()`](https://github.com/tartley/colorama#initialisation) to handle this logic per-`Console`.

**Comment by musse** [comment] 2021-02-05 15:05
Additional context: I'm trying to create a Git pre-commit hook to run a Python script that uses Rich for colored output. When running the pre-commit hook on Linux, everything works fine. When running on Windows, I don't get any colors on any Terminal (Windows Terminal, regular `cmd`, Git Bash). If I run the Python script directly, I do get colors on Windows Terminal and `cmd`, but not on Git Bash. I was able to get colors when running the script directly on Git Bash by setting `PYCHARM_HOSTED=1` (like described on https://github.com/tartley/colorama/issues/224), but I still don't get colors when running it through pre-commit hook on all terminals I've tried. The only way I've managed to get colors with the pre-commit hook is disabling the `colorama.init()` call.

**Comment by willmcgugan** [comment] 2021-02-06 10:00
I think the reason you don't get colors in some environments, is that Colorama strips all ANSI codes if it thinks that it is not writing to a terminal.

> We could use colorama's deinit() and reinit() to handle this logic per-Console. We could use colorama's deinit() and reinit() to handle this logic per-Console.

That might work. The problem is that it has global effect. An app could have several Console instances with different settings, writing in different threads. The ideal solution would be to isolate the Colorama magic to a single Console instance. I briefly tackled that, but didn't manage to make it work.

So I'm not sure what the best solution is. If you were to make any changes, it would have to not break Windows terminal and cmd.exe. Good luck!

**Comment by willmcgugan** [comment] 2021-03-02 08:15
I don’t think there is a great solution to this that doesn’t require reimplementing colorama. Closing for now, but I suspect I will revisit it in future.

**Closed by willmcgugan** 2021-03-02 08:15 UTC
Labels: Needs triage
