### ISSUE TITLE
Texts isn't rendering correctly on Windows

### ISSUE THREAD

**Issue by Niraj-Kamdar** [willmcgugan/rich#135] opened 2020-07-03 13:38 UTC
We are using rich to shows rich and colored text on console but it isn't working properly on Windows.
I have turned on unicode support on my windows. Though on windows it looks like following:
```console
┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                CVE BINARY TOOL                                                                 │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

 • cve-bin-tool Report Generated: 2020-07-03  17:58:41
┌───────────────┐
│ NewFound CVEs │
└───────────────┘

```
but on linux or modern Windows terminal it renders correctly:
```console
╔══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
║                                                                     CVE BINARY TOOL                                                                      ║
╚══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝

 • cve-bin-tool Report Generated: 2020-07-03  17:39:48
╭───────────────╮
│ NewFound CVEs │
╰───────────────╯
```
On Windows github actions it is even unable to render in ASCII (Here is how columns of panel displays on Windows github actions):
```console
\u250c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2510 \u250c\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2510
\u2502CVE-2018-5729\u2502 \u2502CVE-2018-5730\u2502
\u2514\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518 \u2514\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2518
```
On linux everything renders perfectly even in github actions.

**Comment by willmcgugan** [comment] 2020-07-03 13:44
You might want to send me a screenshot, because the Windows version you posted above looks fine. Unless its the lack of double borders you are referring to?

The GH Actions on Windows I've seen before, and can be fixed by setting the environment var `PYTHONIOENCODING="utf8"` .

**Comment by Niraj-Kamdar** [comment] 2020-07-03 13:59
Yes I am referring to bold borders and rounded box. I have viewed the other issue where you have mentioned to use `legacy_windows=False` on Console constructor and it is working properly now. 
![pycharm64_96okTYoRtQ](https://user-images.githubusercontent.com/51387861/86475916-2c3f9d80-bd63-11ea-8f9d-226a7c880e4e.png)

**Comment by willmcgugan** [comment] 2020-07-03 14:07
The double borders and rounded borders don't render on legacy windows when you have raster fonts selected, but work fine with truetype fonts. Unfortunately there is no way to detect which font you are using so they are disabled by default on legacy windows.

Detecting legacy windows is not perfect, it looks at env vars. Here's the code:

```python
def detect_legacy_windows() -> bool:
    """Detect legacy Windows."""
    return "WINDIR" in os.environ and "WT_SESSION" not in os.environ
``` 

Works fine with terminals on your desktop, but may fail on other environments like Github Actions. I haven't found a better way unfortunately.

What config did you use for the screenshot above? There are some blank lines in the top box I can't explain.

**Comment by Niraj-Kamdar** [comment] 2020-07-03 14:19
I am using powershell with utf-8 support turned on. I am using furacode (powerline patched firacode) truetype font.

**Comment by Niraj-Kamdar** [comment] 2020-07-03 14:24
I guess there can be some registry value that stores which font is being set as default for console.

**Comment by willmcgugan** [comment] 2020-07-03 14:34
> I guess there can be some registry value that stores which font is being set as default for console.

Good point, but tbh I'm not sure I want to go to such lengths. The fallback doesn't look too bad, and its not unreasonable to sacrifice a little visual appear when running on an ancient terminal. If you are sure you'll never use raster fonts you can set `safe_box=False` on the Panel and Table classes.

I wonder if the box characters on that font aren't truly the same size as other characters. Would you mind trying the following, and tell me if both lines look the same width.

```
>>> print("═"*50+"\n"+"W"*50)
```

**Comment by willmcgugan** [comment] 2020-07-03 14:39
Ah wait, so in that screenshot you had `legacy_windows=False` ? 

Rich subtracts 1 from the terminal width on legacy windows. This is because a new line character at the end of the line is treated as having a width of 1 and wraps the line (on other terminals it is treated as 0 width).

If you really really want all the box options, setting `safe_box=True` is your only option at the moment.

**Comment by Niraj-Kamdar** [comment] 2020-07-03 14:39
Yes both looks same width.
```console
══════════════════════════════════════════════════
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
```

**Comment by Niraj-Kamdar** [comment] 2020-07-03 15:19
> I guess there can be some registry value that stores which font is being set as default for console.

 I have found registry path that stores current console fonts of current user: `Computer\HKEY_CURRENT_USER\Console`
For cmd it is under: `Computer\HKEY_CURRENT_USER\Console\%SystemRoot%_System32_cmd.exe`
and 
For powershell 32bit it is under: `Computer\HKEY_CURRENT_USER\Console\%SystemRoot%_System32_WindowsPowerShell_v1.0_powershell.exe`
For powershell 64 bit it is under:
`Computer\HKEY_CURRENT_USER\Console\%SystemRoot%_SysWOW64_WindowsPowerShell_v1.0_powershell.exe`
Here, fontface contains name of the font and there is also some meta data about fonts under this registry path.
If somehow we can know current terminal is powershell or cmd and font set is truetype or raster than we can surely tell that texts is going to render or not.

**Comment by willmcgugan** [comment] 2020-07-03 15:49
> If somehow we can know current terminal is powershell or cmd and font set is truetype or raster than we can surely tell that texts is going to render or not.

It would require knowing in advance which fonts render and which don't. You might be right most of the time, until you find one user who installs a custom raster font. I also suspect that those registry keys aren't guaranteed to be the same in the future (v1.0 is a clear indication of that).

Since you can't know with 100% confidence, I think it is safer to disable by default.

**Comment by Niraj-Kamdar** [comment] 2020-07-03 15:50
> Ah wait, so in that screenshot you had `legacy_windows=False` ?
> 
> Rich subtracts 1 from the terminal width on legacy windows. This is because a new line character at the end of the line is treated as having a width of 1 and wraps the line (on other terminals it is treated as 0 width).
> 
> If you really really want all the box options, setting `safe_box=True` is your only option at the moment.

Where am I supposed to add that safe_box=True, As I can see neither Markdown nor Console have optional kwargs safe_box ?
Here is my code:
```python
        console.print(
            Markdown(
                textwrap.dedent(
                    f"""
                    # CVE BINARY TOOL
                    - cve-bin-tool Report Generated: {now}
                    """
                )
            )
        )
```

**Comment by willmcgugan** [comment] 2020-07-03 15:53
It's on the Panel class, used by Markdown. It's not exposed via the Markdown constructor.

**Comment by willmcgugan** [comment] 2020-07-03 16:01
I'll add a parameter to the Console constructor in the next update.

**Comment by willmcgugan** [comment] 2020-07-03 18:29
I've added a `safe_box` parameter to the Console constructor in v3.0.3

**Closed by willmcgugan** 2020-07-03 18:29 UTC

**Comment by Niraj-Kamdar** [comment] 2020-07-03 20:29
Thank you!

**Comment by Niraj-Kamdar** [comment] 2020-07-04 12:34
I have installed latest rich but Panel is still not rendering as expected on Windows. I am still getting those extra lines. 
After some tinkering, I get to know that if we keep `expand=False`, or True with custom width (smaller than max width of window) then Panel will render correctly but if expand is True like in case of Markdown then it will show extra lines.

**Comment by willmcgugan** [comment] 2020-07-04 12:59
I can't reproduce that here. I'll need you to help me find out what is different.

How have you configured the Console? Have you set `legacy_windows`?

What version of Windows? What terminal?

Does the problem rectify itself with a different font?  

What happens when you run this?

```python
from rich.console import Console
c = Console()
print(c.size)
import shutil
print(shutil.get_terminal_size())
```

What does this give you?

```
python -m rich.panel
```

**Comment by Niraj-Kamdar** [comment] 2020-07-04 15:55
Yes I have set `legacy_windows=False`, `safe_box=True` and
```python
from rich.console import Console
c = Console()
print(c.size)
import shutil
print(shutil.get_terminal_size())
```
produces
```console
ConsoleDimensions(width=79, height=24)
os.terminal_size(columns=80, lines=24)
```
output of panel module
```console
❯ python -m rich.panel
<__main__.Panel object at 0x000001A320D61BC8>
┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│┌────────────────────────────┐                                                                                                                  │
││                            │                                                                                                                  │
││        Hello World!        │                                                                                                                  │
││                            │                                                                                                                  │
│└────────────────────────────┘                                                                                                                  │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

```

**Comment by Niraj-Kamdar** [comment] 2020-07-04 15:56
I believe problem is due to incorrect console dimention.

**Comment by willmcgugan** [comment] 2020-07-04 15:58
If you're on legacy windows, the width needs to be reduced by 1. By forcing legacy windows to be False, this isn't happening, which is why you are getting those blank lines.

**Comment by Niraj-Kamdar** [comment] 2020-07-04 16:03
If I keep legacy_windows=None then newlines aren't being printed but rounded box is being replaced by normal box.

**Comment by Niraj-Kamdar** [comment] 2020-07-04 16:05
Can there be any intermediate solution that let windows user get benefit of rich text if it's supported in his system?

**Comment by willmcgugan** [comment] 2020-07-04 16:13
Set `safe_box=False` if you are happy that Windows users with raster fonts may see broken visuals.

> Can there be any intermediate solution that let windows user get benefit of rich text if it's supported in his system?

cmd.exe is over 30 years old. The default setting in Rich ensure the output looks not bad, but you can't expect the same results as more modern software.

Use the new Windows Terminal and you'll have the full experience.

There really isn't any more to say on this issue.
